
#ifndef FOGDECLSPECIFIERENUMS_HXX
#define FOGDECLSPECIFIERENUMS_HXX



class FogDeclSpecifierEnums
{
 //  
 //  	Bit enumerates the bit numbers.
 //  
private:
 enum Bit
 {
  AUTO_BIT,
  CONST_BIT,
  EXPLICIT_BIT,
  EXPORT_BIT,
  EXTERN_BIT,
  FRIEND_BIT,
  INLINE_IF_SHORT_BIT,
  MUTABLE_BIT,
  PRIVATE_BIT,
  PROTECTED_BIT,
  PUBLIC_BIT,
  REGISTER_BIT,
  STATIC_BIT,
  TEMPLATE_BIT,
  TYPEDEF_BIT,
  USING_BIT,
  VIRTUAL_BIT,
  VOLATILE_BIT,
  //  
  INLINE_AS_FRIEND_BIT,
  INLINE_IN_IMPLEMENTATION_BIT,
  INLINE_IN_INTERFACE_BIT,
  NOT_CONST_BIT,
  NOT_INLINE_BIT,
  NOT_STATIC_BIT,
  NOT_VIRTUAL_BIT,
  NOT_VOLATILE_BIT,
  PURE_BIT,
  INVALID_BIT
 };
public:
 //  
 //  	Mask comprises the bit masks.
 //  
 enum Mask
 {
  ZERO = 0,
  AUTO_MASK = 1 << AUTO_BIT,
  CONST_MASK = 1 << CONST_BIT,
  EXPLICIT_MASK = 1 << EXPLICIT_BIT,
  EXPORT_MASK = 1 << EXPORT_BIT,
  EXTERN_MASK = 1 << EXTERN_BIT,
  FRIEND_MASK = 1 << FRIEND_BIT,
  INLINE_IF_SHORT_MASK = 1 << INLINE_IF_SHORT_BIT,
  MUTABLE_MASK = 1 << MUTABLE_BIT,
  PRIVATE_MASK = 1 << PRIVATE_BIT,
  PROTECTED_MASK = 1 << PROTECTED_BIT,
  PUBLIC_MASK = 1 << PUBLIC_BIT,
  REGISTER_MASK = 1 << REGISTER_BIT,
  STATIC_MASK = 1 << STATIC_BIT,
  TEMPLATE_MASK = 1 << TEMPLATE_BIT,
  TYPEDEF_MASK = 1 << TYPEDEF_BIT,
  USING_MASK = 1 << USING_BIT,
  VIRTUAL_MASK = 1 << VIRTUAL_BIT,
  VOLATILE_MASK = 1 << VOLATILE_BIT,
  //  
  INLINE_AS_FRIEND_MASK = 1 << INLINE_AS_FRIEND_BIT,
  INLINE_IN_IMPLEMENTATION_MASK = 1 << INLINE_IN_IMPLEMENTATION_BIT,
  INLINE_IN_INTERFACE_MASK = 1 << INLINE_IN_INTERFACE_BIT,
  NOT_CONST_MASK = 1 << NOT_CONST_BIT,
  NOT_INLINE_MASK = 1 << NOT_INLINE_BIT,
  NOT_STATIC_MASK = 1 << NOT_STATIC_BIT,
  NOT_VIRTUAL_MASK = 1 << NOT_VIRTUAL_BIT,
  NOT_VOLATILE_MASK = 1 << NOT_VOLATILE_BIT,
  PURE_MASK = 1 << PURE_BIT,
  //  
  ACCESS_MASK = PRIVATE_MASK | PROTECTED_MASK | PUBLIC_MASK,
  ANY_CONST_MASK = CONST_MASK | NOT_CONST_MASK,
  ANY_VOLATILE_MASK = VOLATILE_MASK | NOT_VOLATILE_MASK,
  CV_MASK = ANY_CONST_MASK | ANY_VOLATILE_MASK,
  ANY_CV_MASK = CV_MASK,
  INLINE_MASK = INLINE_IF_SHORT_MASK | NOT_INLINE_MASK | INLINE_AS_FRIEND_MASK
     | INLINE_IN_IMPLEMENTATION_MASK | INLINE_IN_INTERFACE_MASK,
  PURE_VIRTUAL_MASK = PURE_MASK | VIRTUAL_MASK,
  ANY_VIRTUAL_MASK = PURE_VIRTUAL_MASK | NOT_VIRTUAL_MASK,
  ANY_STATIC_MASK = NOT_STATIC_MASK | STATIC_MASK,
  STORAGE_CLASS_SPECIFIER_MASK = AUTO_MASK | EXTERN_MASK | MUTABLE_MASK | REGISTER_MASK | ANY_STATIC_MASK,
  FUNCTION_SPECIFIER_MASK = EXPLICIT_MASK | INLINE_MASK | VIRTUAL_MASK | NOT_VIRTUAL_MASK | PURE_MASK,
  TYPE_SPECIFIER_MASK = CV_MASK,
  DECL_SPECIFIER_MASK = STORAGE_CLASS_SPECIFIER_MASK | TYPE_SPECIFIER_MASK | FUNCTION_SPECIFIER_MASK
   | ACCESS_MASK | FRIEND_MASK | TYPEDEF_MASK | EXTERN_MASK,
  META_TYPE_NAME_MASK = TYPEDEF_MASK | USING_MASK,
  META_DECL_SPECIFIER_MASK = META_TYPE_NAME_MASK | ANY_STATIC_MASK | ANY_CONST_MASK,
  //  
  INVALID_ACCESS_MASK = (1 << INVALID_BIT) | ACCESS_MASK,
  INVALID_MASK = (1 << INVALID_BIT) | ((1 << INVALID_BIT)-1)
 };
};
#endif

